--USE WIIZIAUDITORDB_NS
USE WIIZIAUDITORDB_KRAFT
--USE WIIZIAUDITORDB_FISCOPLAN
--USE WIIZIAUDITORDB_AUDITORTESTE
--USE WIIZIAUDITORDB_SUPERMAIS
SELECT e.EmpresaId,e.Cnpj,e.RazaoSocial,e.NomeFantasia,e.Apelido
  FROM Empresas e 
 WHERE e.RazaoSocial LIKE '%UNIMED%'
--  WHERE e.Cnpj LIKE '%06350074%'
  ORDER BY e.RazaoSocial
 

 